# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.csvtoarray:
        class: AppBundle\Services\CsvToArray
    app.elasticsearch:
        class: AppBundle\Services\ElasticSearch
        arguments: ['127.0.0.1:9200']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
